config/routes.rb
WhatTheFuckShouldIEatGMU::Application.routes.draw do
  get "locations/index"

  match ':permalink', :controller => 'pages', :action => 'show', :as => 'my_page'

  root :to => 'locations#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :campus, :building, :warning
  serialize :business_hours

  def to_s
  #	name + aka
  	name
  end


  def available? current_time
  	current_time_as_string = current_time.strftime("%H:%M")

  	# return false if one_off_closings.include? current_time
  	# return true if one_off_openings.include? current_time

  	case current_time.wday #Returns an integer representing the day of the week, 0..6, with Sunday == 0.
  	when 0
  		return true if business_hours["sunday"].include? current_time_as_string
  	when 1
  		return true if business_hours["monday"].include? current_time_as_string
  	when 2
  		return true if business_hours["tuesday"].include? current_time_as_string
  	when 3
  		return true if business_hours["wednesday"].include? current_time_as_string  		
  	when 4
   		return true if business_hours["thursday"].include? current_time_as_string
  	when 5
   		return true if business_hours["friday"].include? current_time_as_string
  	when 6
  		return true if business_hours["saturday"].include? current_time_as_string
  	end	
  	return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
	#here we list all the locations that are open, by default

	@current_time = Time.now
	@current_time_as_string = @current_time.strftime("%I:%M %p")

	@open_locations = Location.all.select {|location| location.available? @current_time}

  end

  def show
    #Not yet implemented
    location = Location.find(params[:id])
  end
  
  def random
  	#this is where you can go to get a random location and food suggestion from one of the places 
  	# => that is currently open
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Where Can I Eat Right Now? (GMU)" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# commenting out the favicon lines in here due to Heroku deploy issues. Will fix later %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

     <%= analytics_init if Rails.env.production? %>

      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Where Can I Eat Right Now? (GMU)</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "About Us", my_page_path('about') %></li>
            </ul>
          </div><!--/.nav-collapse -->
          <p style="font-size: 11px; float:right; margin-top: -5px; color: gray;"><i>More authoritative than the GMU Dining page</i></p>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Updates</li>
              <li><a href="https://twitter.com/gmufoodfinder" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @gmufoodfinder</a></li>
              <li class="nav-header">Authors</li>
              <li><%= link_to "G. S. McNamara", "http://gsmcnamara.com/about"  %></li>
              <li>Aaron Hunter</li>
            </ul>
            <p style="font-size: 14px; color: red;padding-top: 15px;overflow: hidden;"><i>Note: This is not yet accurate for delayed openings and holidays. Hit us up right now if something happened we don't know about: gmu.foodfinder.me@gmail.com or Twitter @gmufoodfinder.</i></p>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <a href="http://incless.com">Inc.less</a> 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :aka, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :aka, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :building, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :building, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :business_hours, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :business_hours, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                locations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Eateries" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:building) %></th>
      <th><%= model_class.human_attribute_name(:campus) %></th>
      <th><%= "AKA" %></th>
    </tr>
  </thead>
  <tbody>
    <% @open_locations.each do |location| %>
      <tr>
       	<!--<td> # link_to location.id, location_path(location) </td>-->
        <td><%= location.name %></td>
        <td><%= location.building %></td>
        <td><%= location.campus %></td>
        <td><%= location.aka %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>It is currently <b><%= @current_time_as_string %></b> at GMU</p>

app/views/locations/show.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @location.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:aka) %>:</strong></dt>
  <dd><%= @location.aka %></dd>
  <dt><strong><%= model_class.human_attribute_name(:building) %>:</strong></dt>
  <dd><%= @location.building %></dd>
  <dt><strong><%= model_class.human_attribute_name(:business_hours) %>:</strong></dt>
  <dd><%= @location.business_hours %></dd>
</dl>

app/views/pages/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "About Us" %></h1>
</div>

<p>Here you can see where you can eat at GMU on any campus at any hour. A mobile app is on the way, and so are more features.</p>

<p>We serve you better than the GMU Dining page because we're more accurate and have the biggest list of dining locations; soon to be included are off-campus options as well.</p>

<p>Hit us up if you have experienced an issue, have input, or want to help out: <a href="mailto:gmu.foodfinder.me@gmail.com">gmu.foodfinder.me@gmail.com</a></p>

<p>Cheers!</p>